{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "billing-service.fullname" . }}-monitor
  labels:
    {{- include "billing-service.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "billing-service.labels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      port: http
      path: /billing-service/actuator/prometheus
{{- end }}