server:
  port: 8000
  servlet:
    context-path: /trade-service

logging:
  level:
    org:
      springframework:
        cloud: error

spring:
  application:
    name: trade-service

  main:
    banner-mode: off

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.globally_quoted_identifiers: true

  config:
    import: "optional:kubernetes:"
  cloud:
    kubernetes:
      reload:
        enabled: true
        strategy: refresh
      config:
        fail-fast: true
      secrets:
        fail-fast: true
    function:
      definition: tradeEvent;bidProcess
    stream:
      bindings:
        tradeEvent-in-0:
          destination: trade
          group: trade
        bidProcess-in-0:
          destination: bids
          group: trade
app:
  purchase-service: http://purchase-service

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    distribution:
      percentiles:
        "[http.server.requests]": 0.5, 0.95, 0.99, 1
      percentiles-histogram:
        "[http.server.requests]": true
      slo:
        "[http.server.requests]": 10ms, 100ms
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true