kafka:
  enabled: true
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT
  controller:
    automountServiceAccountToken: true
  broker:
    automountServiceAccountToken: true
  externalAccess:
    enabled: true
    controller:
      service:
        type: NodePort
    broker:
      service:
        type: NodePort
    autoDiscovery:
      enabled: true
  serviceAccount:
    create: true
  rbac:
    create: true
kafka-ui:
  enabled: true
  envs:
    config:
      KAFKA_CLUSTERS_0_NAME: "otus_l0"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-service:9092"
      AUTH_TYPE: "DISABLED"
      MANAGEMENT_HEALTH_LDAP_ENABLED: "FALSE"

prometheus-kafka-exporter:
  kafkaServer:
    - kafka-service:9092
  prometheus:
    serviceMonitor:
      enabled: true
      namespace: abdalovalex-l10-kafka
      interval: "30s"