@startuml
autonumber
header Начало торгов

"trade service" -> "trade service"
note over "trade service"
    Изменение статуса по крону
end note
queue notification
"trade service" -> notification
notification -> "notification service"
note over "notification service"
    Отправка уведомления
    об изменении статуса закупки
end note

@enduml