{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  application.yml: |-
  {{- toYaml .Values.configMap.applicationData | nindent 4 }}
    spring:
      datasource:
        url: jdbc:postgresql://{{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql }}:{{ .Values.postgresql.global.postgresql.service.ports.postgresql }}/{{ .Values.postgresql.global.postgresql.auth.database }}
{{- end }}
