{{- if .Values.ingress.enabled -}}
{{- $fullName := include "purchase-service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "purchase-service.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://auth-service.abdalovalex-l10-auth-service.svc.cluster.local/auth-service/auth/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/auth-service/auth/login"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-ROLE, X-USER-ID"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
