apiVersion: v1
kind: Service
metadata:
  name: {{ include "purchase-service.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "purchase-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "purchase-service.selectorLabels" . | nindent 4 }}
